[build]
  command = "npm install && npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-optional"

[functions]
  included_files = ["node_modules/**/*"] 